### ISSUE TITLE
Rework Sharing Dialog in Settings

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#104]
![image](https://user-images.githubusercontent.com/35893306/58122756-9d2d0000-7c0a-11e9-83a8-9c0a221eb5a1.png)

**Comment by ildyria** [comment]
I'm hesitating to assign @bennettscience on it. :innocent:

**Comment by bennettscience** [comment]
uh...😳

**Comment by SerenaButler** [comment]
Just as a direction. The mobile view needs rework sometimes.

![image](https://user-images.githubusercontent.com/35893306/58316985-27e14b00-7e15-11e9-94ab-d1b25ce12639.png)
