### ISSUE TITLE
UI Issues when "About"-Sidebar is active

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#115]
### Detailed description of the problem

- Next-Button is hidden behind sidebar so not functional.
- When sidebar is active, image should be not overlapped by sidebar but still centred in the remaining view area

![lychee_ui_sidepane_bug_01](https://user-images.githubusercontent.com/35893306/52850168-223be100-3113-11e9-9515-e94ef4c9e5fa.png)
![lychee_ui_sidepane_bug_02](https://user-images.githubusercontent.com/35893306/52850169-223be100-3113-11e9-85c3-15ecbf552b69.png)
![lychee_ui_sidepane_bug_03](https://user-images.githubusercontent.com/35893306/52850170-223be100-3113-11e9-80b4-44506f686d9a.png)

**Comment by kamil4** [comment]
I just submitted a PR that should make it all consistent: no content overlap in any of the albums/album/photo views, irrespective of the layout used for the album view. Right now we have this inconsistent... mess that, IMHO, is more of an emergent behavior from a series of patches piled on top of each other than a result of conscious design decisions. In particular, justified layout was the only one where the sidebar would overlap photos in album view, but even that seemed accidental (e.g., try to resize the window in that situtation and see what happens).
