### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by kenokenobingo** [LycheeOrg/Lychee-front#126]
A documentation for the front-end would be cool. In particular, I’m wondering where to change the location Lychee loads the photos from.

**Comment by ildyria** [comment]
I don't understand your question. The URLs are provided by the back end.

Sure the JavaScript code is lacking a bit of documentation but the API interface has already be described (see API.md)

⁣--

Kind regards

Benoît Viguier

sent from my phone.​

Le 28 juin 2019 à 19:10, à 19:10, K E N O <notifications@github.com> a écrit:

**Comment by ildyria** [comment]
I don't understand your question. The URLs are provided by the back end.

Sure the JavaScript code is lacking a bit of documentation but the API interface has already be described (see [https://github.com/LycheeOrg/Lychee-front/blob/master/API.md](API.md))

**Comment by kenokenobingo** [comment]
> I don't understand your question. The URLs are provided by the back end.

How does the front-end get the URLs from the back-end?

**Comment by ildyria** [comment]
yes. Basically you query a photo with `API/Photo::get` given an `photoID` and `albumID` and as a result you get a bunch of information, including the urls of the pictures for each size.

**Comment by ildyria** [comment]
Fixed with the updated API file in the wiki of Lychee-Laravel.

**Comment by kenokenobingo** [comment]
Thanks! :)
