### ISSUE TITLE
Proposal: start the gallery with visibility: hidden;

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-front#135]
I think it looks pretty ugly when on page reload, at least in Firefox, for a moment those huge icons get displayed as in [the first FAQ](https://github.com/LycheeOrg/Lychee/wiki/FAQ#lychee-is-not-working).

As I understand it, this happens because the CSS is not loaded yet so the browser renders using its built-in style.

I tested adding `style='visibility: hidden;'` to `div#container` and clearing it from JS (which runs after the document is ready). It works, although the footer could in principle still be displayed.

A more thorough solution would be to add the above property to the `html` tag. However, `layouts.simple`, where `html` is defined in Lychee-Laravel, is used by multiple blades. I don't use the landing page or any of the rest so I don't know if they are affected by this problem as well or is it just the gallery, so I don't know if it's worth modifying the generic layout and then adding code to each page's JS or should I make a new layout just for the gallery?

Let me know what you think...

**Comment by SerenaButler** [comment]
I can't reproduce it on any browser ... I know it happens sometimes when checking stuff or coding css but usually it is fine.

**Comment by kamil4** [comment]
Yeah, I don't know if it depends on the phase of the moon or what but sometimes I can reproduce it very easily and other times not...

**Comment by ildyria** [comment]
@kamil4 fixed ?

**Comment by kamil4** [comment]
Yes, fixed via #137. One thing to keep in mind is that this changes the behavior of Lychee front end when the permissions are wrong, so the FAQ needs to be updated. Hence, I'm keeping this issue open for now, changing the labels as appropriate.
