### ISSUE TITLE
Feature request: Fade to next Picture

### ISSUE THREAD

**Issue by hwende** [LycheeOrg/Lychee-front#141]
Could we have a setting for the next-picture-animation.
Fade to next Picture (via black or directly) would be really nice!

Sincerely
Henning Wende

**Comment by kamil4** [comment]
FYI, I moved your request to the Lychee-front repository.

As to the nature of your request, Lychee UI is surprisingly user-configurable; you just need to know which knob to tweak. Try the following in `user.css`:

```
#imageview #image {
    animation-name: fadeIn;
    animation-duration: 3s;
}
```

**Comment by hwende** [comment]
I see...
This is really awesome!
Didn't realize how to work with user.css
Thank's a lot!

Regards
Henning Wende
