### ISSUE TITLE
[Enhancement] Show album description between nav and pics

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee-front#166]
It would be nice to have option to show album description between the nav and the pictures in every album. This would give context to the user if the album name does not cut it. I know that it can be found behind the info button but that is not something regular/never before used user finds.

optionally it would be nice to have it as an admin (for all) and user (by album) setting to change visibility of this description.

**Comment by haivala** [comment]
It is related if the admin setting is done for this.

Can you hint me where/how I can add this? file?

Thank you!

**Comment by ildyria** [comment]
The admin part will need some laravel backend implementation but this is quite minimal. You can have a look at how `full_photo` is implemented. :)

**Comment by SerenaButler** [comment]
You mean UI like this:

![image](https://user-images.githubusercontent.com/35893306/68377915-81330180-014b-11ea-86bf-081d3330da77.png)

**Comment by haivala** [comment]
@SerenaButler well I thought only to have the description like in the mockup

**Comment by MikeTheTux** [comment]
I would like to request that the Description can optionally be shown in the album gallery as well:
![grafik](https://user-images.githubusercontent.com/44850211/152654170-d41d5f54-2fea-4e0c-bbb6-bcf0d58bc18c.png)
