### ISSUE TITLE
link not copied to clipboard

### ISSUE THREAD

**Issue by 46dude** [LycheeOrg/Lychee-front#167]
Chromium Versión 77.0.3865.90 (Build oficial) Built on Ubuntu , running on LinuxMint 19.2 (64 bits)
When i try to share one album with the option "direct link" it appears a green bar with a text saying the link is already in the clipboard" ( ready to paste ) but i cant paste it. Ctrl-v is empty, middle mouse button empty too. Not using any adblocker or extension.

**Comment by ildyria** [comment]
Please wait a bit, a developer should be here soon to assist you.

**Comment by kamil4** [comment]
Is your gallery served over https? Clipboard support in Chrome does not work for websites that don't use encryption...

**Comment by 46dude** [comment]
Its not under https, so no webpage cant copy things to my clypboard if its
not using https?

**Comment by kamil4** [comment]
In principle it should work as we have a fallback code to handle the case when our preferred way to access the clipboard is not available. But apparently it doesn't work with Chrome. I'll need to check if that's a fundamental limitation or merely a bug in our fallback code. Stay tuned...

**Comment by 46dude** [comment]
Thank you so much
