### ISSUE TITLE
Collapsing sidebar style issues

### ISSUE THREAD

**Issue by bluser86** [LycheeOrg/Lychee-front#177]
### Detailed description of the problem

When closing the left sidebar the label text drops to a new line below the icon because of the collapsing div. It seems applying a `min-width: 210px;` to the class `.linkMenu` fixes this issue.

Another thing I noticed is that all but the Settings menu items have a preceeding whitespace which causes the items to look misaligned. 

Apologies for being nitpicky :) 

### Steps to reproduce the issue

Open and close the sidebar. You can see a glimpse of the text being pushed to a newline before the sidebar completely closes.

### Browser and system

Chromium Version 79.0.3945.117 (Official Build) Arch Linux (64-bit)
Firefox Version 72.0.1 Arch Linux (64-bit)

**Comment by tmp-hallenser** [comment]
Do you want to create a PR for us to test?

**Comment by bluser86** [comment]
Sure, no problem!
