### ISSUE TITLE
Album thumbnails are not working

### ISSUE THREAD

**Issue by khanpeach** [LycheeOrg/Lychee-front#198]
Hi

The album thumbnails are not generated for the created albums but "recent album" shows the thumbnail only for the recent folder

in the log i can see following error

App\Metadata\GitHubFunctions::__construct -- 47 -- file_get_contents(/home/xxx/.git/HEAD): failed to open stream: No such file or directory

any idea why?

**Comment by d7415** [comment]
Please file this at [LycheeOrg/Lychee](https://github.com/LycheeOrg/Lychee/issues/new/choose) using the template there.

**Comment by ildyria** [comment]
> App\Metadata\GitHubFunctions::__construct -- 47 -- file_get_contents(/home/xxx/.git/HEAD): failed to open stream: No such file or directory

This just means that it is not finding `.git/HEAD` which is normal if you are using the release channel.
