### ISSUE TITLE
Album text on white background

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee-front#25]
### Detailed description of the problem
This is a fringe case, but when an album thumbnail is white, you cannot see the subfolder icon or the album title. See [#27](https://github.com/LycheeOrg/Lychee-Laravel/issues/27).

### Steps to reproduce the issue
Upload a new image to an album that is mostly white. Use Lychee-Laravel for the subfolder icon.

![image](https://user-images.githubusercontent.com/3878010/51077522-d27e7b80-1675-11e9-9250-717cb5833883.png)

It may be worth increasing the bottom gradient. Not sure about ways to solve the subfolder issue other than to maybe invert the icon colors? That doesn't look too great, though.

**Comment by ildyria** [comment]
I solved the border for the sub folder icon with one of the previous commit.

However I have not found a way to add a shadow under the icon. (I am not really a fan of adding a shaddow just like the one in bottom on the top of the picture.

**Comment by evoludolab** [comment]
The remaining part of this issue should now be resolved too. A drop shadow has been added to the subfolder marker/counter in PR #364 and was merged in (1ce260f).
