### ISSUE TITLE
Mov files get imported with thumbnail but only sound is played

### ISSUE THREAD

**Issue by sebrep** [LycheeOrg/Lychee-front#258]
When I import movies from the server the movie is shown besides the images, there is a thumbnail for the movie but only sound is played. Some movies play though, mostly old and small ones. The import was done with the "symlinks" option. 
Is this related to any other php.ini settings I have to add on top of the one's below?

Import movies from the Iphone X with the latest software as a mov file into lychee. I have the following options for php:
post_max_size = 512M
upload_max_filesize = 256M 
date.timezone = Europe/Berlin
lychee is running with mysql.

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (release):        4.3.0
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          256M
    Max post size:                   512M
    MySQL Version:                   10.5.9-MariaDB-1:10.5.9+maria~focal
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1802
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040300
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2000
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

Lychee is running on a linux machine with mysql I'm browsing it through firefox latest version.

**Comment by kamil4** [comment]
This typically indicates that the video codec is not supported by your web browser. Lychee simply uses the HTML5 `<video>` tag to play the movie files; it doesn't modify them in any way. Thumbnail extraction works because we use `ffmpeg` for that, which has a very broad video codec support. Web browsers, however, are typically a lot more limited.

Quite possibly, your files are encoded using the H.265 (HEVC) codec. If you can post a sample video file I can have a look, or inspect it yourself using, e.g., `ffprobe`. Try recoding them into H.264 before uploading and they will probably play just fine.

**Comment by sebrep** [comment]
Yes sorry. It is indeed H.265. After noticing that I check in the issues and am aware that supporting this is not in the realm of what you want to do and I understand why. So I will try to reformat all my videos ...

Thanks for the answer.
