### ISSUE TITLE
Album view: wrong line breaks when scrollbars are visible

### ISSUE THREAD

**Issue by nicokaiser** [LycheeOrg/Lychee-front#386]
When the viewport is smaller than 640px, either 4 thumbnails (>=568px) or 3 thumbnails (<568px) are displayed.
The size of the thumbnails is calculated as `--size: calc((100vw - 3px) / 4)` [here](https://github.com/LycheeOrg/Lychee-front/blob/1ce260f4d09bd7b9073316cc22a076150cb995bd/styles/main/_content.scss) – which is fine _if_ there is no scollbar visible.

However when the browser shows a scrollbar, this calculation is wrong and leads to early line breaks like in this example:

![Bildschirm­foto 2023-01-28 um 18 40 03](https://user-images.githubusercontent.com/238631/215282339-b0920a8f-e458-47e9-abb7-3cda6fa26d06.png)

Changing the `--size` varible to something like `calc((100% - 3px) / 4)` does not solve the problem, since `--size` is being reused in other elements where 100% is something completely different.

Any ideas how to fix this in CSS?

**Comment by ildyria** [comment]
Fixed.
