### ISSUE TITLE
Link for Logs is invalid

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/Lychee-front#405]
### Detailed description of the problem
The link for 'Show Logs' is incorrect.
It should not be "/Logs" but "Logs" unless Lychee is installed at the root of the website.

### Steps to reproduce the issue
Install Lychee in a subdirectory so that it is available at something like https://example.com/Lychee/public/

Clicking on 'Show Logs'  will send to https://example.com/Logs instead of https://example.com/Lychee/public/Logs

### Output of the diagnostics (Settings => Diagnostics)
```
    System Information
    --------------
    Lychee Version (release):                4.9.4
    DB Version:                              4.9.4
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.2.7
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/Paris
    Max uploaded file size:                  500M
    Max post size:                           500M
    Max execution time:                      200
    MySQL Version:                           10.11.3-MariaDB-1
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.
```

### Browser and system
Not relevant

### proposed patch:
```patch
diff --git a/scripts/main/lychee.js b/scripts/main/lychee.js
index 45da938..42ada65 100644
--- a/scripts/main/lychee.js
+++ b/scripts/main/lychee.js
@@ -286,7 +286,7 @@ lychee.diagnostics = function () {
  * @returns {string}
  */
 lychee.logs = function () {
-	return "/Logs";
+	return "Logs";
 };
 
 /**
```

On the generated `public/dist/frontend.js` file I had to modify:
```
 */leftMenu.Logs=function(){leftMenu.closeIfResponsive();window.open("/Logs");};/+++**
```
into
```
 */leftMenu.Logs=function(){leftMenu.closeIfResponsive();window.open("Logs");};/+++**
```
I am not sure my patch is correct as I have not regenerated the .js files.

**Comment by ildyria** [comment]
I use the docker 4.9.4 and I can confirm that this has been resolved. So I'm not sure where this goes wrong.

**Comment by LudovicRousseau** [comment]
Sorry. It is a problem on my side. I was still using the `public/dist/` from the previous Lychee version. It is because of a bug in my upgrade script.

The Logs window is just a empty grey window. I do not see any logs when I display images.
I have:
```
LOG_VIEWER_ENABLED=true                                                         
```
Do I have to enable something else?

**Comment by ildyria** [comment]
I think this is probably because the CSP is not disabled in the logs. For now I would say the easiest way is to go into `configs/secure-header.php` and disable the CSP.

I am not sure how to handle that edge case of sub directories.

**Comment by LudovicRousseau** [comment]
Exact. I edited `config/secure-headers.php` to disable CSP and the logs window now works.
Thanks
