### ISSUE TITLE
Album View // About // Share Settings

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#49]
It makes no sense to show that when not logged in ;-)

It's obviously public, not hidden nor password protected ... :-P And the owner ... I wrote about :-D

![image](https://user-images.githubusercontent.com/35893306/54143209-ab4fea80-4429-11e9-8d26-e90bc61e8d02.png)

**Comment by ildyria** [comment]
Note, this still means that this info should not be returned by the server when in public mode.
