### ISSUE TITLE
Lazy load thumbnails

### ISSUE THREAD

**Issue by alex-phillips** [LycheeOrg/Lychee-front#60]
When you have hundreds of photos in an album, the frontend makes a request for all of the thumbnails at once causing reduced performance. I propose that a lazy load technique is implemented so that thumbnails don't actually get requested until they are scrolled into view. This should also make the thumbnails load in faster since they're only requested when in view.

I'm more than happy to take on this issue, but wanted to make sure it was something that would be accepted first.

**Comment by ildyria** [comment]
I like the idea. What would be the result in the sense of how would it interact with e.g. the Justified layout?
Would the pictures just bee filled with grayed placed holder until you actually scroll to them?
Would you still be able to load the full page little by little, e.g. once the first batch of thumbnail is received you query for the next batch?

By lazy load do you mean that the thumbnail don't appear until they are scrolled over (like facebook)? If so do you think this it possible to have it as a setting to enable (either via the `more...` or via an actual toggle button)?

**Comment by alex-phillips** [comment]
What I'm experimenting with now is that the layout and page load would be exactly the same but the "image" would be a blank placeholder until you scrolled to it, yes. Not sure if this would be a config option you can toggle or not, that depends on the library I use. Should that be a requirement as I look into doing this?

**Comment by ildyria** [comment]
not necessarily a requirement, but if the page still load completely while you are not scrolling (like first load the part you are scrolling and then load the rest) then I think it is fine.

One of the use case is you want to show a specific picture to someone but you don't really remember where it is in your album aside from it is in the bottom. How would that work with the lazy loading? :)

**Comment by alex-phillips** [comment]
How would you normally do that now? Just jump all the way to the bottom?

**Comment by ildyria** [comment]
yup and let firefox / chrome / IE load those pictures first. :)

**Comment by ildyria** [comment]
It takes my browser about 1.2 s to fully load this page with 472 pictures : https://photography.viguier.nl/gallery#1551392811988

**Comment by alex-phillips** [comment]
Right, so with what I'm doing, if you just hit "page down" then it will jump to the bottom of the page and only load those images. It will probably load the ones at the top first as well since the page loads at the top, but you skip over the ones in the middle so they shouldn't get loaded.

I'm about to submit a PR. Give it a test drive and let me know what you think.

**Comment by ildyria** [comment]
:+1:

**Comment by alex-phillips** [comment]
PR submitted. This will also make mobile performance much better as well as saving on bandwidth.

**Comment by kamil4** [comment]
@ildyria FYI, your gallery page took 28.85s to load for me... And that's with a >100Mbps download link. So I certainly think that what @alex-phillips proposes has value :smile:

**Comment by ildyria** [comment]
:smile:
