### ISSUE TITLE
Album View not updated when moving images to a different (sub)folder

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#63]
* Created a subalbum
* Moved the first approx. 10 images to the subalbum
* Get back to the Album view
* Space of the moved images is "empty"

![image](https://user-images.githubusercontent.com/35893306/54071376-1358d200-426c-11e9-97dc-5083cbb001f1.png)

**Comment by kamil4** [comment]
I'm having trouble reproducing it. Could you elaborate on the steps? Here's what I don't understand:

Step 1: _Created a subalbum_. That switches the view to that newly created subalbum, right?

Step 2: _Moved the first approx. 10 images to the subalbum_. How do you do that? I'm not aware of any way to move images from another album to the currently displayed one -- am I missing something? Do you exit the subalbum between steps 1 and 2? Also, do you move the images in bulk or one by one? Does it make a difference that it's 10 and not just 1 or 2?

Step 3: _Get back to the Album view_. Get back from where? Were you in the subalbum in Step 2 then? How did you move them then? :astonished:

**Comment by SerenaButler** [comment]
@kamil4 I can't reproduce it either anymore ... and I can't remember exactly the behaviour at this time but I think it after you moved images you were refered to album the images where moved too. This behaviour is now different. So I think we can close this here.

**Comment by kamil4** [comment]
I managed to produce this effect after all... though not for Move, but for Delete. Anyway, will be fixed in my next PR...

**Comment by SerenaButler** [comment]
It's still there ... :-( So guess we need to reopen.

Movin image:

![image](https://user-images.githubusercontent.com/35893306/56369382-86ede780-61f9-11e9-850f-ff2d1d185119.png)

Next image will be shown:

![image](https://user-images.githubusercontent.com/35893306/56369398-8f462280-61f9-11e9-80c9-02c5af8ecf9b.png)

Going back to the album - see the gap:

![image](https://user-images.githubusercontent.com/35893306/56369430-9ff69880-61f9-11e9-9474-8bb8707e3dad.png)

**Comment by kamil4** [comment]
Right, so it still doesn't rejustify when Move or Delete is invoked from the photo view. Should be easy enough to fix...
