### ISSUE TITLE
Reset/Leave Search

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#64]
Reset/Leave search (e.g. X in search box or Back-Button). There is no way resetting a search but deleting the search text.

**Comment by SerenaButler** [comment]
I found out that a "x" is allready there. Haha. To see change e.g. user.css:

.header__clear {
    opacity: 1;
}

I guess the idea was to just show the x in certain cases, e.g. allready searched.

**Comment by kamil4** [comment]
Yeah, that search results view needs to be cleaned up. I feel that it should be its own view (like album and photo views) but right now it's just a modified albums view which is confusing both to the user and to when coding the front end.

**Comment by kamil4** [comment]
This was fixed in #107, I believe.
