### ISSUE TITLE
Searched Image // Back Button Behaviour wrong 

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#65]
When clicking an Image within a search result, the back button at the image page should point (back) to the searched image results, **NOT** the Album of the image.

**Comment by kamil4** [comment]
I looked into it and I'm cautiously optimistic that it may be easier to solve than it seems. The search results are internally a (temporary) album. Right now that album is discarded when switching to the photo view (i.e., clicking on an image). But if we keep it and reprogram the behavior of the Back button, it should work. I'm sure there will be all sorts of tricky corner cases when a user tries to edit the results, but the basic use case should be doable...

**Comment by alex-phillips** [comment]
Any chance this could get looked at? Would love this feature when browsing hundreds of photos organized by tags
