### ISSUE TITLE
Settings Menu behaviour when in image view

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#80]
* Start in Albums View
* Open Settings so that Settings sidebar is open
* Open an album
* Click on Settings Menu Entry
* Settings are opend
**-> Good**

------------

* Start in Albums View
* Open Settings so that Settings sidebar is open
* Open an album
* Open an Image (image view)
* Click on settings menu entry
* Header title change from image name to "Settings"
* Settings are NOT opend
**-> Bad**

------------

![image](https://user-images.githubusercontent.com/35893306/56284656-719f8d00-6115-11e9-83e2-c97619ab824c.png)

* click browser back button
* Settings are opened with Albums Header Title

![image](https://user-images.githubusercontent.com/35893306/56284670-782e0480-6115-11e9-9636-7d1c7deab625.png)

**Comment by kamil4** [comment]
There are two ways to fix this. One is to fix the displaying of Settings in the photo view, the other is to hide the sidebar in anything but the albums view :wink:. My guess is that whoever wrote this code didn't consider the possibility of invoking Settings in the photo view. There's a reason why the cogwheel is only visible in the albums view, after all.
