### ISSUE TITLE
Import for Dropbox 

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#81]
If no Dropbox Key is set the menu entry "Import for Dropbox" should a) not vissible or b) when selecting should give a "warning" that a dropbox key has to be set. Right now just nothing happens.

**Comment by ildyria** [comment]
I am in favor of **a**.

Also this should be easily implementable:
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/contextMenu.js#L8

**Comment by d7415** [comment]
> I am in favor of **a**.

Agreed

**Comment by eisenlohr** [comment]
From a usability perspective, option b) with a proper explanation of what steps need to be taken to make Dropbox importing work seems the better alternative.

I am new to Lychee and have gone through creating a Dropbox app, inserted the associated key under "advanced options", but clicking on "Import from Dropbox" still does nothing...

```
Diagnostics
-----------
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version (json):  3.2.14
Lychee Version (git):   65930ee (master)
DB Version:             update_030214
System:                 Linux
PHP Version:            7.3
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1690
GD Version:             2.2.5
Plugins:                


Config Information
------------------
checkForUpdates:         1
default_license:         none
deleteImported:          0
full_photo:              1
image_overlay:           0
image_overlay_type:      exif
imagick:                 1
lang:                    en
layout:                  1
medium_max_height:       1080
medium_max_width:        1920
php_script_limit:        0
skipDuplicates:          1
small_max_height:        360
small_max_width:         0
sortingAlbums:           ORDER BY id DESC
sortingPhotos:           ORDER BY takestamp DESC
useExiftool:             1
version:                 update_030214

```
