### ISSUE TITLE
Wording in Album View

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#82]
"all" should be "selected"

![image](https://user-images.githubusercontent.com/35893306/56356439-2fd81a80-61d9-11e9-8503-4fb1076f28e6.png)

"Root" should be "Home" or "Start" or "Albums" (root is a technical term for most users;-))

![image](https://user-images.githubusercontent.com/35893306/56356068-213d3380-61d8-11e9-8b49-ea0eebb87308.png)

**Comment by ildyria** [comment]
Well... you can edit this file and make a PR: https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Locale/English.php 
:smiley:
