### ISSUE TITLE
Selecting Subalbums not possible

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#83]
I would expect the same behaviour as with albums, being able to select subalbums to e.g. delete more the one at once. Trying to catch a subalbum results in:

![image](https://user-images.githubusercontent.com/35893306/56356907-682c2880-61da-11e9-89af-0faa12be72a8.png)

**Comment by ildyria** [comment]
Try to create multiple sub albums and delete them by selecting WITHOUT selecting pictures.

**Comment by SerenaButler** [comment]
Yepp, that is  working, so the problem is in what I posted in the next issue ;-) No "unselecting" when "reselecting" :-)

**Comment by ildyria** [comment]
Thus... not an issue. :smile:

**Comment by SerenaButler** [comment]
Indeed :-D
