### ISSUE TITLE
No "unselecting" possible

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#84]
When select items with rubberband no "unselecting" is possible, e.g. click in empty space and no "reselecting" is possible, using rubberband again. Only a click on a image, going in image view with the need to going back to album view is working.

![image](https://user-images.githubusercontent.com/35893306/56357155-23ed5800-61db-11e9-9cfb-2daf11b36f56.png)

**Comment by SerenaButler** [comment]
AFTER the context menu was in use unselecting by clicking on the background IS possible ;-)

**Comment by kamil4** [comment]
This one's done -- #116 will fix it when merged (hint, hint :wink:).

**Comment by kamil4** [comment]
Closed via #116.

**Comment by SerenaButler** [comment]
Not fixed, sorry .Still not working :-(

**Comment by kamil4** [comment]
Did you recompile the front end (`npm run compile`)? The precompiled version in the `Lychee-Laravel` repo does not include those fixes yet.

**Comment by SerenaButler** [comment]
Ok that might be the reason. But can't do that on my hosting. I wait then ;-)

**Comment by kamil4** [comment]
OK, try again -- @ildyria updated the generated files as part of his recent big merge.

**Comment by SerenaButler** [comment]
Working! :-)
