### ISSUE TITLE
Update Button Behaviour after Update

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-front#96]
After Update-Button has clicked it should get hidden to avoid another click resulting in: Error: Check for update failed.

**Comment by ildyria** [comment]
you don't get an update failed. The failure appear only in the case of a failure to fetch server side. But this is normal behaviour.

**Comment by SerenaButler** [comment]
That's not what I meant :-) If an update has done the update button should not showed anymore because there is nothing to update as the update were done seconds ago ;-)

**Comment by ildyria** [comment]
it will not be showing if you reload the page in question. :stuck_out_tongue:
