### ISSUE TITLE
Add "copy link" to context menu

### ISSUE THREAD

**Issue by Naielc** [LycheeOrg/Lychee-front#98]
1.Hope can add image by using drop upload.
2.Add a one-click copy share link in right click menu, work in album and single image.

**Comment by d7415** [comment]
> 1.Hope can add image by using drop upload.

Yes, Lychee does this.

> Add menu option to copy the share URL address.

I could get behind a "copy" button in the existing share menu. I don't see significant benefit of putting it into the context menu (which is already at 7 items and a spacer)

**Comment by Naielc** [comment]
Enter the photo album-->Click on the eyes-->ctrl+c
Right click album-->on the copy option
I think the second is more convenient to copy the share link

**Comment by d7415** [comment]
3 clicks vs 2. And that ignores that afterwards there's a:

- Change application/window
- Click to the correct place
- Paste

I'm unconvinced that this makes a significant enough difference to enough users to warrant an extra item in the context menu.

**Comment by ildyria** [comment]
> Enter the photo album-->Click on the eyes-->ctrl+c
> Right click album-->on the copy option
> I think the second is more convenient to copy the share link

if the album is already in a sharable mode:
Enter the photo album --> `F6` (select address bar) -> `Ctrl` + `C`
